language: ruby
before_install:
  - gem install bundler

bundler_args: --without debugger

script:
  - rake test

notifications:
  email:
  - ngiger@ywesee.com
rvm:
  - ruby-head
  - 2.1.2
  - 1.9.3
  - 1.8.7
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.9.3
