language: ruby
before_install:
  - gem install bundler

bundler_args: --without debugger

script:
  - bundle exec rake test

notifications:
  email:
  - ngiger@ywesee.com
rvm:
  - 2.7.1
  - 2.5.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
